# Ruby


pool:
  vmImage: 'Ubuntu 16.04'
  addToPath: true

steps:
- task: ArchiveFiles@1
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/'
    includeRootFolder: false
    verbose: true
    quiet: true
    #archiveType: 'zip'
    #archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    #replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
